### ISSUE TITLE
Does this script still install java6 ?

### ISSUE THREAD

**Issue by PoohSunny** [johnlim/setup#2]
I read a comment in the script.

`# install JDK 1.6x for IntelliJ compatibality reasons`

is it still valid concern ? I thought the latest IntelliJ IDEA works against java7+

**Comment by johnlim** [comment]
Hi @PoohSunny, I've updated the script (see commit 3437a8827420a47ca57e8ad820b0c46ec5ab686e)  to use sdkman to manage java versions so it's no longer a concern :)
